---
title: "da_history"
format: html
editor: source
---

```{r setup}
#| include: false

library(tidyverse)
library(janitor)
library(openxlsx)

dashboard_info <- read_csv("data/solano_dashboard.csv") %>%
  clean_names() %>%
  filter(countyname == "Solano") %>%
  select(
    cds,
    districtname,
    countyname,
    schoolname,
    charter_flag,
    studentgroup,
    student_group_long
  ) %>%
  distinct()

assistance <- read_csv("data/assistance.csv") %>%
  clean_names() %>%
  left_join(dashboard_info, by = join_by(cds, studentgroup, charter_flag)) %>%
  filter(countyname == "Solano", assistance != "*") |>
  mutate(
    da_level = case_when(
      (ec52072b_2025 == "Y" |
        ec52072_2024 == "Y" |
        ec52072_2023 == "Y" |
        ec52072_2022 == "Y") ~ "Direct Technical Assistance",
      ec52071f_2025 == "Y" ~ "Targeted Differentiated Assistance",
      TRUE ~ "Differentiated Assistance"
    )
  )

```

```{r clean_assistance}
# echo: false

assistance_table <-
  assistance %>%
  mutate(leaname = if_else(is.na(charter_flag), districtname, schoolname)) %>%
  select(
    "Reporting Year" = reportingyear,
    "County" = countyname,
    "LEA" = leaname,
    "DA Level" = da_level,
    "Student Group" = student_group_long,
    "Priorities" = assistance
  ) %>%
  mutate(
    description = case_match(
      Priorities,
      "A" ~ "Met Criteria in Priority Areas 4, 5, and 6",
      "B" ~ "Met Criteria in Priority Areas 4 and 5",
      "C" ~ "Met Criteria in Priority Areas 5 and 6",
      "D" ~ "Met Criteria in Priority Areas 4 and 6",
      "E" ~ "Met Criteria in Priority Areas 4 and 8",
      "F" ~ "Met Criteria in Priority Areas 5 and 8",
      "G" ~ "Met Criteria in Priority Areas 6 and 8",
      "H" ~ "Met Criteria in Priority Areas 4, 5, and 8",
      "I" ~ "Met Criteria in Priority Areas 4, 6, and 8",
      "J" ~ "Met Criteria in Priority Areas 5, 6, and 8",
      "K" ~ "Met Criteria in Priority Areas 4, 5, 6, and 8"
    )
  ) %>%
  arrange(`Reporting Year`, LEA)

leas <-
  assistance_table |>
  pull(LEA) |>
  unique()

for (lea in leas) {
  lea_file <-
    lea |>
    str_remove(":") |>
    str_replace_all(" ", "_") |>
    str_to_lower()

  assistance_table |>
    filter(LEA == lea) |>
    write.xlsx(paste0("data_output/", lea_file, "_da_assistance_history.xlsx"))
}

openxlsx::write.xlsx(assistance_table, "data_output/da_assistance_history.xlsx")

```